# Site settings
title:          Chongxiao's Blog
description:    "Sharing Chongxiao's thinkings, views, and experiences."
url:            https://chongxiao-li.github.io

# Author
author:
  name:         Chongxiao Li
  email:        chongxiao_li@outlook.com
  url:          https://inelaah.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: chongxiao_li@outlook.com
  github: https://github.com/Chongxiao-Li
  linkedin: https://www.linkedin.com/in/chongxiao-li/
